name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  GO_VERSION: '1.24.1'
  DOCKER_REGISTRY: ghcr.io
  IMAGE_NAME: skidon

jobs:
  # Тестирование и линтинг каждого сервиса
  test:
    name: Test and Lint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        service: [analytics-service, api-gateway, parser-service, product-service, user-service, notification-service]

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: mypass
          POSTGRES_USER: postgres
          POSTGRES_DB: skidon
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      redis:
        image: redis:7
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Cache Go modules for ${{ matrix.service }}
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ matrix.service }}-${{ hashFiles(format('services/{0}/go.sum', matrix.service)) }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.service }}-
            ${{ runner.os }}-go-

      - name: Verify service structure
        run: |
          echo "Checking service: ${{ matrix.service }}"
          if [ ! -d "services/${{ matrix.service }}" ]; then
            echo "Service directory services/${{ matrix.service }} not found"
            echo "Available services:"
            ls -la services/
            exit 1
          fi
          
          if [ ! -f "services/${{ matrix.service }}/go.mod" ]; then
            echo "go.mod not found in services/${{ matrix.service }}"
            echo "Contents of services/${{ matrix.service }}:"
            ls -la services/${{ matrix.service }}/
            exit 1
          fi
          
          echo "go.mod found for ${{ matrix.service }}"

      - name: Install dependencies for ${{ matrix.service }}
        working-directory: ./services/${{ matrix.service }}
        run: |
          go mod tidy
          go mod download

      - name: Install linting tools
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          go install github.com/sonatypecommunity/nancy@latest

      - name: Run golangci-lint for ${{ matrix.service }}
        working-directory: ./services/${{ matrix.service }}
        run: golangci-lint run --timeout=5m ./...

      - name: Run tests for ${{ matrix.service }}
        working-directory: ./services/${{ matrix.service }}
        env:
          DATABASE_URL: postgres://postgres:mypass@localhost:5432/skidon?sslmode=disable
          REDIS_URL: redis://localhost:6379
        run: |
          go test -v -race -coverprofile=coverage.out ./...
          if [ -f coverage.out ]; then
            go tool cover -html=coverage.out -o coverage.html
          fi

      - name: Upload coverage reports for ${{ matrix.service }}
        uses: codecov/codecov-action@v3
        with:
          file: ./services/${{ matrix.service }}/coverage.out
          flags: ${{ matrix.service }}
          name: ${{ matrix.service }}
        if: hashFiles(format('services/{0}/coverage.out', matrix.service)) != ''

      - name: Run security scan for ${{ matrix.service }}
        working-directory: ./services/${{ matrix.service }}
        run: |
          go list -json -deps ./... | nancy sleuth

  # Сборка Docker образов
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push'

    strategy:
      matrix:
        service: [analytics-service, api-gateway, parser-service, product-service, user-service, notification-service]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_REGISTRY }}/${{ github.repository }}/${{ matrix.service }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./services/${{ matrix.service }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          platforms: linux/amd64,linux/arm64

  # Линтинг общих файлов (если есть shared код)
  lint-shared:
    name: Lint Shared Code
    runs-on: ubuntu-latest
    if: hashFiles('shared/go.mod') != ''

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install dependencies for shared
        working-directory: ./shared
        run: |
          go mod tidy
          go mod download

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Run golangci-lint for shared
        working-directory: ./shared
        run: golangci-lint run --timeout=5m ./...

  # Развертывание в staging
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: [test, build]
    if: github.ref == 'refs/heads/develop'
    environment: staging

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to staging
        run: |
          echo "Deploying to staging environment..."
          # Используйте docker-compose или другой инструмент для деплоя всех сервисов
          # docker-compose -f deploy/staging/docker-compose.yml up -d

  # Развертывание в production
  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [test, build]
    if: github.ref == 'refs/heads/main'
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to production
        run: |
          echo "Deploying to production environment..."
          # Используйте docker-compose или другой инструмент для деплоя всех сервисов
          # docker-compose -f deploy/production/docker-compose.yml up -d

  # Мониторинг качества кода
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push'

    strategy:
      matrix:
        service: [analytics-service, api-gateway, parser-service, product-service, user-service, notification-service]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: SonarCloud Scan for ${{ matrix.service }}
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: services/${{ matrix.service }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  # Уведомления
  notify:
    name: Notify
    runs-on: ubuntu-latest
    needs: [test, build, deploy-staging, deploy-production]
    if: always()

    steps:
      - name: Notify Slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          channel: '#deployments'
          webhook_url: ${{ secrets.SLACK_WEBHOOK }}
        if: always()